### ISSUE TITLE
Atari Jaguar background appears blank

### ISSUE THREAD

**Issue by Kelvfimer** [dm2912/Crystal#11]
Hello

I PR Atari Jaguar to Emuelec https://github.com/EmuELEC/EmuELEC/commit/9478f5a3a1c272f8e4be5736e43f8c976b2b9ea5

I see that there are assets for atari jaguar but when adding the platform, the icon backgound appears blank

![Atari Jaguar blank icon screen](https://user-images.githubusercontent.com/85133404/215670346-f82a5e56-b40b-45b8-bf79-0c442f318aa6.jpeg)

and inside detail page a backgound an image appears

![Atari Jaguar](https://user-images.githubusercontent.com/85133404/215670416-d6d088d0-1ea3-4903-a3f5-03c4157dc31b.jpeg)

I used atari jaguar theme in emuelec

 <name>atarijaguar</name>
    <fullname>Atari Jaguar</fullname>
    <manufacturer>Atari</manufacturer>
    <release>1993</release>
    <hardware>console</hardware>
    <path>/storage/roms/atarijaguar</path>
    <extension>.j64 .jag .J64 .JAG .zip</extension>
    <command>emuelecRunEmu.sh %ROM% -P%SYSTEM% --core=%CORE% --emulator=%EMULATOR% --controllers="%CONTROLLERSCONFIG%"</command>
    <platform>atarijaguar</platform>
    <theme>atarijaguar</theme>
    <emulators>
      <emulator name="libretro">
        <cores>
          <core default="true">virtualjaguar</core>
        </cores>
      </emulator>
    </emulators>
  </system>

Please can you review why I can have the blank screen on crystal theme? 

thx

**Comment by dm2912** [comment]
hmm, weird, will have a look

**Comment by dm2912** [comment]
ok, everything in the theme is just named "jaguar", im not sure when it became "atarijaguar".. 

will fix

**Comment by dm2912** [comment]
should be fixed with https://github.com/dm2912/Crystal/commit/f824b54c56b3b7eabf7e12d22a00ef2373d547d2
