### ISSUE TITLE
Adding PGM and PGM2 theme

### ISSUE THREAD

**Issue by 25minutes** [dm2912/Crystal#12]
Would it be possible to add themes for PGM and PGM2 please? There are quit a lot great arcade games on them. 

The following link gives more details of them:
https://en.wikipedia.org/wiki/PolyGame_Master

**Comment by dm2912** [comment]
Added in https://github.com/dm2912/Crystal/commit/43f80b3972f98cb67a61713d9cd83255dec0ee97

Logo's arent perfect as had to do them from scratch :D
