### ISSUE TITLE
Some art is missing, have a fix

### ISSUE THREAD

**Issue by TadMSTR** [dm2912/Crystal#13]
Some art is missing when in use due to differences in filenames. Copying 3 files fixed it for me.

for background and logos, where needed
copy mame.* to mame2003.*
copy pce-cd.* to pcenginecd.*
copy tic-80.* to tic80.*

**Comment by dm2912** [comment]
weird. Is this in emuelec? everything defined in the systems xml matches artwork.

But.. have added all the extra files, and also added it to systems if its not an emuelec thing

https://github.com/dm2912/Crystal/commit/c3defe52675ee01d5d756c5b8ea51f437f2fb1c2

**Comment by TadMSTR** [comment]
using a theme forked from here for a device using emulation station. sorry I didn't mention that. some of the device folders didn't match, or were not there. I found this fixed it for me. told the author of the fork and he said to submit here.

https://github.com/farfenkugell/es-theme-farfenkugell_crystal

**Comment by farfenkugell** [comment]
I did not ask to submit anything :D I only answered that it is not my theme, but a modification of an existing one.

**Comment by TadMSTR** [comment]
my apologies then. misunderstood your reply.

**Comment by TadMSTR** [comment]
sorry for the confusion. I had found that many EmuELEC themes work on other distros using ES, such as ArkOS. 
when looking at the files I found that a simple copy and rename fixed it.

thanks for the quick reply on this regardless

**Comment by dm2912** [comment]
> sorry for the confusion. I had found that many EmuELEC themes work on other distros using ES, such as ArkOS. when looking at the files I found that a simple copy and rename fixed it.
> 
> thanks for the quick reply on this regardless

yeh, many do, but as I only use emuelec personally, I do not tailor it to work with anything beyond that. and it becomes too difficult to maintain with other systems that use different theme strings in the system config files.
