### ISSUE TITLE
Add Vircon32 theme

### ISSUE THREAD

**Issue by 25minutes** [dm2912/Crystal#15]
Vircon32 core has been available in Retroarch. Could you please add the theme for Vircon32?

http://www.vircon32.com/index.html has more info about this 32-bit virtual console.

**Comment by dm2912** [comment]
somehow i missed this. will do it when i do apple2

**Comment by dm2912** [comment]
https://github.com/dm2912/Crystal/commit/4b88c7b143bd530a8039b226676f47734466c229
