### ISSUE TITLE
Add Ikemen-go to Crystal Theme

### ISSUE THREAD

**Issue by Kelvfimer** [dm2912/Crystal#17]
Hello @dm2912 

Thx to @Diegrosan we will have Ikemen go in Emuelec. I wanted if you can create a theme for it. 

https://ikemen-engine.github.io/

https://mugen.fandom.com/wiki/Ikemen

thx!!

**Comment by dm2912** [comment]
https://github.com/dm2912/Crystal/commit/fb379817f72ceb06cd329ab05c239bf85b40b0c1
