### ISSUE TITLE
Adding Amstrad GX-4000 theme

### ISSUE THREAD

**Issue by wouaco** [dm2912/Crystal#5]
Would it be possible to add a theme for GX-4000 from Amstrad please?
I currently run it through Amstrad CPC, but would be great to have a dedicated theme.

Great Job anyway !! Really looking good !!
Thanks

**Comment by dm2912** [comment]
do you mean as a collection? because it does not appear to be in es_systems.cfg as a system?

**Comment by dm2912** [comment]
will theme it and ask shanti to add it to EE as a system

**Comment by dm2912** [comment]
theming done, wallpaper, panels, logos. 

you will just need to either add gx4000 to es_systems or do as a collection. :D
