### ISSUE TITLE
music

### ISSUE THREAD

**Issue by Gedehamsen021** [dm2912/Crystal#9]
what is the music of dreamcast title?

**Comment by dm2912** [comment]
sorry for late reply. github decided to not email me about issues. 

music should be same as wallpaper, which from memory was shenmue?

**Comment by Gedehamsen021** [comment]
yes is shenmue wallpaper but i not found the song in any place

**Comment by dm2912** [comment]
https://downloads.khinsider.com/game-soundtracks/album/shenmue-1999-dreamcast-gamerip

track 15

but, i think the file may have broken, just updating now
